# Generated by Django 3.2 on 2023-08-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_not_me',
        ),
    ]
