# Generated by Django 3.2 on 2023-08-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230810_1538'),
        ('users', '0002_auto_20230810_1601'),
    ]

    operations = [
    ]
