# Generated by Django 3.2 on 2023-08-11 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_auto_20230810_1538_0002_auto_20230810_1601'),
        ('users', '0004_alter_user_options'),
    ]

    operations = [
    ]
