# Generated by Django 3.2 on 2023-08-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_confirmation_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_not_me',
        ),
    ]
